name: Run Unit Tests

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
      - staging

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          python-version: 3.13

      - name: install dependencies
        run: |
          uv venv .venv
          source .venv/bin/activate
          uv pip install .[dev]

      - name: Run pytest
        run: |
          source .venv/bin/activate
          pytest tests
